# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e874f28eb5971149f77b82ea750fb6c158c5b8b77424ece587a713e8d561efddbc834e28972d50b4fbb915be104512a54c893a43c1b1b8d3ed00605f951f698

test:
  secret_key_base: be7f929ae73948bba63f2c43f9396d95c233f0805f786d13a8704cecd20230d2bb7751a484d5c06ae8b2730effe711dab655d77b85e87397a9bfe57152bd4c02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
